spring:
  application:
    name: 'fornecedor'
  h2:
    console:
      enabled: true
      path: /console-database
  datasource:
    username: sa
    password: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: 'create-drop'
    database-platform: org.hibernate.dialect.H2Dialect
