spring:
  application:
    name: 'fornecedor'
  h2:
    console:
      enabled: true
      path: /console-database
  datasource:
    username: 34rfDsdF!
    password: s34343@13
    url: jdbc:h2:mem:fornecedor_prod_db
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: 'create'
    database-platform: org.hibernate.dialect.H2Dialect